__version__ = "0.1.0"
__title__ = "NFSim"
__description__ = "Neurofeedback simulation"
__url__ = "https://github.com/salnat/NFSim.git"
__doc__ = __description__ + " <" + __url__ + ">"
__author__ = "Saleh Natour"
__email__ = "salnat145@gmail.com"
__license__ = "MIT"